language: swift
osx_image: xcode9

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.4.2
install:
  - bundle install --without=documentation
script:
  - set -o pipefail
  - xcodebuild clean build test -scheme Features-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | bundle exec xcpretty -f `bundle exec xcpretty-travis-formatter`
